# Generated by Django 5.0.7 on 2024-07-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Vegetable', 'Vegetable'), ('Meat', 'Meat'), ('Dairy', 'Dairy'), ('Otherr', 'Otherr')], default='Otherr', max_length=20),
        ),
    ]
